name: Build & Test

on:
  pull_request:
    branches:
      - develop
      - "feat*"
  merge_group:
    types: [checks_requested]
    branches: 
      - develop
      - "feat*"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-workflow:
    name: PR Workflow
    # If any dependent jobs fails, this WF skips which won't block merging PRs
    # calling always() is required for this WF to run all the time
    
    runs-on: ubuntu-latest
    needs:
      - java-gradle-integration
    steps:
      - name: report-failure
        if: |
          needs.java-gradle-integration.result != 'success'
        run: exit 1
      - name: report-success
        run: exit 0

  java-gradle-integration:
    name: ${{ matrix.os }} / ${{ matrix.python }} / java gradle
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        python:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - run: make init
      - run: gradle --status
      - run: gradle --stop
      - run: gradle --status
      - run: pytest -vv tests/integration/workflows/java_gradle
